apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: docker.io/busybox:1.28.4 #1.28.4之后的版本有问题，例如下面截图报错可以ping不可以使用nslooup解析
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
